"""
FX Radiant — Signals Router
=============================
Endpoints for reading the SMC signal history:

    GET  /api/signals                          → All recent signals (newest first)
    GET  /api/signals/{instrument}             → Signals for one instrument only
    GET  /api/signals/latest                   → The single most recent signal across all instruments

Signals are generated by the background task in main.py and stored in
app.core.database.signal_history. This router only reads — it never
writes signals (that is the engine's job).
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.core.database import signal_history
from app.core.security import get_current_user

router = APIRouter(prefix="/signals", tags=["Signals"])


# ── All signals ───────────────────────────────────────────────────────────────

@router.get(
    "",
    summary="Get all recent SMC signals across all instruments",
)
async def get_all_signals(
    limit: int = Query(default=100, ge=1, le=500, description="Max signals to return"),
    _: dict = Depends(get_current_user),
) -> list[dict]:
    """
    Returns the most recent SMC trade signals across all instruments,
    sorted newest-first.

    Each signal in the list contains:
      • instrument, direction (LONG/SHORT), entry, sl, tp, breakeven, rr
      • confidence (always 100 — signals only fire at full confluence)
      • layer1/layer2/layer3 diagnostic info
      • timestamp (Unix epoch seconds)

    Signals are kept in memory (last 50 per instrument).
    In production, persist these to a database for historical analysis.
    """
    all_signals: list[dict] = []
    for instrument_signals in signal_history.values():
        all_signals.extend(instrument_signals)

    # Sort newest first by timestamp
    all_signals.sort(key=lambda s: s.get("timestamp", 0), reverse=True)

    return all_signals[:limit]


# ── Latest signal ─────────────────────────────────────────────────────────────

@router.get(
    "/latest",
    summary="Get the single most recent signal across all instruments",
)
async def get_latest_signal(
    _: dict = Depends(get_current_user),
) -> dict:
    """
    Returns the single most recently fired signal, or raises 404 if
    no signals have fired yet in this session.
    """
    all_signals: list[dict] = []
    for instrument_signals in signal_history.values():
        all_signals.extend(instrument_signals)

    if not all_signals:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No signals have fired yet. All 3 SMC layers must align first.",
        )

    return max(all_signals, key=lambda s: s.get("timestamp", 0))


# ── Per-instrument signals ────────────────────────────────────────────────────

@router.get(
    "/{instrument}",
    summary="Get signal history for a specific instrument",
)
async def get_instrument_signals(
    instrument: str,
    limit: int = Query(default=50, ge=1, le=100),
    _: dict = Depends(get_current_user),
) -> list[dict]:
    """
    Returns the signal history for one instrument only.
    Useful for the detail drawer's history tab.

    Raises 404 if the instrument is not in the supported list.
    """
    if instrument not in signal_history:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Instrument '{instrument}' not found. "
                   f"Supported: {list(signal_history.keys())}",
        )

    return signal_history[instrument][:limit]